name: Deploy Flutter Web App

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.0'  # Specify your Flutter version

    - name: Install dependencies
      run: flutter pub get

    - name: Build Flutter web
      run: flutter build web

    - name: Deploy to FTP server
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        ftp-server: ftp://your-ftp-server.com
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: build/web
        server-dir: /r1330880/to/your/webapp/drikkeleker/
