name: Deploy Flutter Web App

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.4'  # Specify your Flutter version

    - name: Install Dart SDK
      uses: dart-lang/setup-dart@v1
      with:
        sdk: '3.5.4'  # Specify the required Dart SDK version

    - name: Verify Dart SDK version
      run: dart --version

    - name: Change to Flutter project directory
      run: cd mer

    - name: Install dependencies
      run: |
        flutter pub get
        flutter upgrade
      working-directory: mer

    - name: Build Flutter web
      run: flutter build web
      working-directory: mer

    - name: Deploy to SSH server
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "mer/build/web/*"  # Use wildcard to include all files and directories inside 'web'
        target: "/webroots/r1330880/drikkeleker/"