name: Deploy Flutter Web App

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.4'  # Specify your Flutter version

    - name: Install Dart SDK
      uses: dart-lang/setup-dart@v1
      with:
        sdk: '3.5.4'  # Specify the required Dart SDK version

    - name: Verify Dart SDK version
      run: dart --version

    - name: Change to Flutter project directory
      run: cd mer

    - name: Install dependencies
      run: |
        flutter pub get
        flutter upgrade
      working-directory: mer

    - name: Build Flutter web
      run: flutter build web
      working-directory: mer

    - name: Deploy to SFTP server
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: "mer/build/web/"
        remote_path: "/r1330880/to/your/webapp/drikkeleker/"
        remote_host: ${{ secrets.SFTP_HOST }}
        remote_user: ${{ secrets.SFTP_USERNAME }}
        remote_key: ${{ secrets.SFTP_KEY }}  # Add your SSH private key to GitHub secrets